apiVersion: v1
kind: ConfigMap
metadata:
  name: socialpublish-config
  namespace: socialpublish
data:
  LISTEN_ADDR: "0.0.0.0:8080"
  REDIS_ADDR: "redis:6379"
  FFMPEG_BIN: "ffmpeg"
  S3_REGION: "us-east-1"
  S3_ENDPOINT: ""
  S3_BUCKET: "socialpublish-media"
