apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: socialpublish-secrets
  namespace: socialpublish
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: socialpublish-secret-store
    kind: SecretStore
  target:
    name: socialpublish-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: socialpublish/database
        property: url
    - secretKey: s3-access-key-id
      remoteRef:
        key: socialpublish/s3
        property: accessKeyId
    - secretKey: s3-secret-access-key
      remoteRef:
        key: socialpublish/s3
        property: secretAccessKey
