apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: socialpublish
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: socialpublish
            - name: POSTGRES_USER
              value: socialpublish
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: socialpublish-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: socialpublish
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: socialpublish-postgres-secret
  namespace: socialpublish
type: Opaque
data:
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
